### ISSUE TITLE
Need data

### ISSUE THREAD

**Issue by LookMumNoBackup** [jacob-heglund/raildelay#1]
I stumbled over your paper and found the idea really cool. 
That's why I wanted to clone your repository and try it out locally.

Unfortunately I found no data in the repo and also no links where I can get them. If understood your code/paper correctly you get the data from a public API which responses in JSON, than transform the relevant data into a CSV and than use these data for training.

Could you please provide some example files or at least a schema of the files your algorithm expects to find on my local filesystem. I could than try to implement a projection of data I can get (e.g. from the same API you used) to your schema and try out your algorithm.

Many thanks!

**Comment by jaye-heglund** [comment]
Hi, thanks for your interest in the project! I updated the readme for this repo with a link to a public-facing version of this project. 

We made the data available via a Google Drive link, so you should be able to get everything working if you follow the instructions in the readme in that repo.

Thanks again!
